name: Code Review - PROD

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize]
    paths:
      - "*"
      - "!infra/*"
      - "!.github/*"
  push:
    branches:
      - EC-406-devops-decommissioning
      
jobs:
  deploy_on_prod:
    uses: pagopa/dx/.github/workflows/legacy_code_review.yaml@CES-11-add-legacy-templates #./.github/workflows/deploy-pipelines.yaml
    name: Code Review on PROD
    secrets: inherit